=== puntowav/marques/exam/exemple.dtd
<!ELEMENT exemple_complert (agenda?,productes?)>
<!ELEMENT agenda (contacte*,productes*)>
<!ELEMENT contacte (nom, cognom+, tlf, email?, adreca,comandes)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT adreca (carrer, num, cp)>
<!ELEMENT carrer (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT comandes (comanda)>
<!ELEMENT comanda (productecom)>
<!ELEMENT productecom (#PCDATA)>
<!ELEMENT productes (producte+)>
<!ELEMENT producte (#PCDATA)>
<!ATTLIST tlf pais CDATA  #REQUIRED>
<!ATTLIST contacte dni ID  #REQUIRED>
<!ATTLIST producte id ID  #REQUIRED>
<!ATTLIST productecom id_prod IDREF #REQUIRED>

=== puntowav/marques/exam/exemple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE exemple_complert SYSTEM "exemple.dtd">
<exemple_complert>
    <agenda>
        <contacte dni="G44444444">
            <nom></nom>
            <cognom></cognom>
            <tlf pais="es">935555555</tlf>
            <email></email>
            <adreca>
                <carrer></carrer>    
                <num></num>
                <cp></cp>
            </adreca>
            <comandes>
                <comanda>
                    <productecom id_prod="a01">
                    </productecom>
                </comanda>
            </comandes>
        </contacte>
    </agenda>
    
    <productes>
        <producte id="a01"></producte>
    </productes>
</exemple_complert>
